# You can use this file to create a conda environment for this pipeline:
# conda env create -f environment.yml
name: vcf2maf
channels:
  - conda-forge
  - bioconda
  - defaults

dependencies:
  - bioconda::ensembl-vep=106.1
  - bioconda::genesplicer=1.0
  - bioconda::htslib=1.10.2
  - bioconda::bcftools=1.10.2
  - bioconda::samtools=1.10
  - bioconda::ucsc-liftover=377
